### PR TITLE
Named Routes Support

### PR DESCRIPTION
**Pull request by arunoda**
Read this: #57 

Named Routes is pretty important. We can have it.
Let's do it.
But we need to make named routes optional. Route must be define with a route definition.

If you like to implement the named route support. Just send a PR to this.
Let work on that on this branch.

Once everything is good, let's merge it to the master and do a release.

### CODE REVIEW

**Comment by arunoda** [comment]
Related to #57

**Comment by arunoda** [comment]
We've a PR on this: https://github.com/meteorhacks/flow-router/pull/62

**Comment by jhuenges** [comment]
@arunoda any update on when the update is going to happen?

**Comment by arunoda** [comment]
Will be merged in few days. All good here.

**Comment by arunoda** [comment]
Published with: 1.2.0
Docs: `https://github.com/meteorhacks/flow-router#using-route-name-instead-of-the-pathdef`

**Comment by delgermurun** [comment]
:+1: 

btw, my commits didn't squashed :(

**Comment by arunoda** [comment]
If I did it, your commits will get deleted. 
Anyway, I don't mind having those in the history. Since we are doing `git merge --no-ff`, everything is fine.
And `git lol` make it pretty.

**Comment by janat08** [comment]
Let me get this right, you're still essentially writing out the path but with the use of vars?

**Pull request closed without merging**
