### PR TITLE
FlowRouter.getRouteName() + tests

### PR DESCRIPTION
**Pull request by gadicc**
As per #105.  Very simple PR just following the scheme of `getParams()`, etc.  You can see which test you prefer (or if you want to keep both); I think *registration* is enough since everything else is tested already elsewhere, but wrote a fuller test too for the sake of completeness.

### CODE REVIEW

**Comment by gadicc** [comment]
Sorry, simplified the 2nd test... will rebase if you're happy.

**Comment by arunoda** [comment]
Yeah. Rebase it :) I'll look at this in few hours :)

**Comment by arunoda** [comment]
Thanks @gadicc. This is perfect. I've added some docs.
Merged and released as `v1.7.0`.

**Comment by gadicc** [comment]
Damn, always forget the docs :>  Thanks for your quick attention to this.  Super helpful for some work and discussions on famous-views atm.

**Comment by arunoda** [comment]
Great.

**Pull request merged**
