### PR TITLE
 Fix 135, 130: Implement "path" method on server & remove trailing slash

### LINKED ISSUE #130: Ugly named route group '/' urls
Example: user group routes (named)
```js
var usersGroup = FlowRouter.group({
  prefix: '/admin/users'
});

usersGroup.route('/', {
  name: 'admin.users.index',
  action: function () {
    FlowLayout.render('adminBasicLayout', {main: 'adminUsersIndex'});
  }
});

usersGroup.route('/create', {
  name: 'admin.users.create',
  action: function () {
    FlowLayout.render('adminBasicLayout', {main: 'adminUsersCreate'})
  }
});
```

Now we want a link for a named route
```js
FlowRouter.path('admin.users.index');
```

The route for the **/** action will be:
```
http://localhost:3000/admin/users/
```

The last **/** is very ugly, can we remove it?

### PR DESCRIPTION
**Pull request by delgermurun**
Add support for #135.
Fix #130.

### CODE REVIEW

**Comment by delgermurun** [comment]
@arunoda I pushed fix for #130 to it. Is it fine :)?

**Comment by arunoda** [comment]
Looks good to me. Will take this today.

**Comment by arunoda** [comment]
Published and released as 1.11.0

**Comment by rclai** [comment]
Can you guys address [this issue](https://github.com/meteorhacks/flow-router/issues/130#issuecomment-112442534).

**Pull request merged**
