### PR TITLE
Add group routes support

### PR DESCRIPTION
**Pull request by arunoda**
Read this: #57 

When we are writing a lot of routes. It's better to have group routes.
I'm quite not sure about the api.

It should be kind a familiar API. May be we can have something like sub routes feature in picker.
see: https://github.com/meteorhacks/picker#filtering-and-sub-routes

Send a PR to this branch.

### CODE REVIEW

**Comment by delgermurun** [comment]
We have a PR on it #69

**Comment by arunoda** [comment]
I think we can merge this release to the master and do a 1.x release since we don't break anything.

@delgermurun So, how do we add docs for group routes.
I think having a new section under [route definitions](https://github.com/meteorhacks/flow-router#routes-definition) works best.

**Comment by delgermurun** [comment]
@arunoda Yeah, that's best place. Do you want me to write docs :)?

PS: My English isn't good :D

**Comment by arunoda** [comment]
Ha ha.
Anyway, I'll do it.

**Comment by arunoda** [comment]
Released with version `1.3.0`

**Pull request merged**
